// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bestSinksCnew
List bestSinksCnew(Rcpp::List& pp, Rcpp::List& ms, Rcpp::List& po, Rcpp::List& pps, Rcpp::List& ppss, Rcpp::List& bps, Rcpp::List& mydata);
RcppExport SEXP _causnet_bestSinksCnew(SEXP ppSEXP, SEXP msSEXP, SEXP poSEXP, SEXP ppsSEXP, SEXP ppssSEXP, SEXP bpsSEXP, SEXP mydataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ms(msSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type po(poSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type pps(ppsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ppss(ppssSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type bps(bpsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type mydata(mydataSEXP);
    rcpp_result_gen = Rcpp::wrap(bestSinksCnew(pp, ms, po, pps, ppss, bps, mydata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_causnet_bestSinksCnew", (DL_FUNC) &_causnet_bestSinksCnew, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_causnet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
