# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Set equal for lists
#'
#' Returns logical vector with index of where y is equal to x.
#'
#' It is assumed that y only appears in x once and that all vectors in x are
#' sorted.
#'
#' @param x list of integer vectors
#' @param y integer vectors
#'
#' @export
list_setequal <- function(x, y) {
    .Call(`_causnet_list_setequal`, x, y)
}

