# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
getIndex <- function(m, T) {
    .Call(`_causnet_getIndex`, m, T)
}

#' @export
getSubsetFromIndex <- function(n, r) {
    .Call(`_causnet_getSubsetFromIndex`, n, r)
}

#' @export
getwsinkscores <- function(w, w_networkscore, pp, po, pps, bps, m) {
    .Call(`_causnet_getwsinkscores`, w, w_networkscore, pp, po, pps, bps, m)
}

#' @export
getIthColumn <- function(vy, i) {
    .Call(`_causnet_getIthColumn`, vy, i)
}

#' @export
display <- function(vy) {
    invisible(.Call(`_causnet_display`, vy))
}

#' @export
display1 <- function(vy) {
    invisible(.Call(`_causnet_display1`, vy))
}

uniq <- function(input) {
    .Call(`_causnet_uniq`, input)
}

#' @export
bestSinksCnew <- function(pp, ms, po, pps, ppss, bps, mydata) {
    .Call(`_causnet_bestSinksCnew`, pp, ms, po, pps, ppss, bps, mydata)
}

