# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function to find the Best Sink
#'
#' @export
#' @param pp list
#' @param ms list
#' @param po list
#' @param pps list
#' @param ppss list
#' @param bps list
#' @param mydata list
bestSinksCnew <- function(pp, ms, po, pps, ppss, bps, mydata) {
    .Call(`_causnet_bestSinksCnew`, pp, ms, po, pps, ppss, bps, mydata)
}

